version: '3.4'
services:
  db:
    command: mysqld --default-authentication-plugin-mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: Admin357/
      MYSQL_USER: root
      MYSQL_PASSWORD: Admin357
      MYSQL_DATABASE: db_life_match
    ports:
      - "3308:3306"
    networks:
      - generation-network
  lifematch:
    restart: always
    build: ./lifematch
    working_dir: /lifematch
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./lifematch:/lifematch
      - ~/.m2:/root/.m2
    ports:
      - "9000:8000"
    command: mvn clean spring-boot:run
    links: 
      - db
    depends_on:
      - db
    networks:
      - generation-network

networks:
   generation-network:
    driver: bridge 